image: node:20-alpine

stages:
  - install_dependencies
  - build
  - deploy

variables:
  SSH_USER: pandit
  SERVER_IP: 213.130.147.149
  # SERVER_IP: 54.166.222.34
  DEPLOY_PATH: /home/pandit/devlaps-client-projects/keejani/client
  PRIVATE_KEY_PATH: /tmp/private_key # Use a temporary file for the private key

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install_dependencies
  script:
    - npm ci --force

build:
  stage: build
  script:
    - npm run build
    - ls "$(pwd)"
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Add server to known_hosts to avoid interactive prompt
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Set up the private key from the environment variable
    - echo "$SSH_PRIVATE_KEY" > $PRIVATE_KEY_PATH
    - chmod 600 $PRIVATE_KEY_PATH

    # Transfer files and restart nginx on the server
    - scp -r -i $PRIVATE_KEY_PATH "$(pwd)"/dist/keejani-client/browser $SSH_USER@$SERVER_IP:$DEPLOY_PATH
    - ssh -i $PRIVATE_KEY_PATH $SSH_USER@$SERVER_IP "sudo systemctl restart nginx"

    # Clean up the private key for security
    - rm -f $PRIVATE_KEY_PATH
