image: node:20-alpine

stages:
  - install_dependencies
  - build
  - deploy

variables:
  SSH_USER: ubuntu
  SERVER_IP: 213.130.147.149
  DEPLOY_PATH: /home/pandit/devlaps-client-projects/keejani/client

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install_dependencies
  script:
    - npm ci --force

build:
  stage: build
  script:
    - npm run build
    - apk add --no-cache openssh-client

deploy:
  stage: deploy
  script:
    # Ensure SSH client is available
    - apk add --no-cache openssh-client

    # Create SSH directory and known_hosts file
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Add server's SSH host key to known_hosts
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Write the private key from the environment variable
    - echo "$SSH_PRIVATE_KEY" > /tmp/private_key
    - chmod 600 /tmp/private_key

    # Copy build files to the server
    - scp -i /tmp/private_key -r "$(pwd)"/dist/keejani-client/browser $SSH_USER@$SERVER_IP:$DEPLOY_PATH

    # Restart the server application
    - ssh -i /tmp/private_key $SSH_USER@$SERVER_IP "sudo systemctl restart nginx"

    # Clean up private key
    - rm -f /tmp/private_key
