image: node:20-alpine

stages:
  - deploy

variables:
  SSH_USER: pandit
  SERVER_IP: 213.130.147.149
  PRIVATE_KEY_PATH: /builds/pandit.alabi/keejani-client/my-gcp-key
  DEPLOY_PATH: /home/pandit/devlaps-client-projects/keejani/client

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  script:
    # Install dependencies and build the project
    - npm i --force
    - npm run build

    # Install SSH client
    - apk add --no-cache openssh-client

    # Ensure SSH directory exists
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Add server to known_hosts
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Set up SSH
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - chmod 400 $PRIVATE_KEY_PATH
    - eval $(ssh-agent -s)

    # Clean existing deployment and copy new files
    - ssh -i $PRIVATE_KEY_PATH $SSH_USER@$SERVER_IP "rm -rf $DEPLOY_PATH/*"
    - scp -r -i $PRIVATE_KEY_PATH dist/* $SSH_USER@$SERVER_IP:$DEPLOY_PATH/


    - ssh -i $PRIVATE_KEY_PATH $SSH_USER@$SERVER_IP "sudo systemctl restart nginx"
