image: node:20-alpine

stages:
  - install_dependencies
  - build
  - deploy

variables:
  SSH_USER: ubuntu
  SERVER_IP: 51.20.93.126
  DEPLOY_PATH: /home/ubuntu/buyer
  PRIVATE_KEY_PATH:  /builds/devs1632222/Keejani/my-gcp-key

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install_dependencies
  script:
    - npm ci --force

build:
  stage: build
  script:
    - npm run build
    -  ls "$(pwd)"
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - pwd
    -  ls "$(pwd)"
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - chmod 400 $PRIVATE_KEY_PATH
    - eval $(ssh-agent -s)
    - scp -r -i $PRIVATE_KEY_PATH "$(pwd)"/dist/keejani-client/browser/* $SSH_USER@$SERVER_IP:$DEPLOY_PATH
    - ssh -i $PRIVATE_KEY_PATH  $SSH_USER@$SERVER_IP "sudo systemctl restart nginx"

# deploy:
#   stage: deploy
#   image: node:20-alpine
#   before_script:
#     - apk add --no-cache openssh-client
#     - mkdir -p ~/.ssh
#     - pwd
#     -  ls "$(pwd)"
#     - chmod 700 ~/.ssh
#     - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#   script:
#     - chmod 400 $PRIVATE_KEY_PATH
#     - eval $(ssh-agent -s)
#     - scp -r -i $PRIVATE_KEY_PATH /builds/pandit.alabi/cotenant/dist $SSH_USER@$SERVER_IP:$DEPLOY_PATH/temp_dist
#     - ssh -i $PRIVATE_KEY_PATH  $SSH_USER@$SERVER_IP "sudo systemctl restart nginx"
